name: text-to-teamwork
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.6
  - pip
  - pip:
    - streamlit>=1.29.0,<2.0.0
    - pandas>=2.2.0,<2.3.0
    - openpyxl>=3.1.0,<3.2.0
    - openai>=1.12.0,<2.0.0
    - python-dotenv>=1.0.0,<2.0.0
    - protobuf>=3.20,<6 